#!/bin/bash

#################################################
## general settings

#################################################
## custom commands
alias vi='nvim'

#################################################
## jupyter notebook
if ps -ef | grep "jupyter" | grep "Python" > /dev/null
then
    echo "Already running"
else
    nohup jupyter notebook --no-browser --allow-root &
fi

#################################################
## git status
function gbr {
    git status --short 2> /dev/null 1> /dev/null
    if [ "$?" -ne "0" ]; then
        return 1
    else
        branch="`git branch --list | grep '^\*' | cut -c 3-`"
        branch_str="\033[1;031m$branch\033[0m"

        stat=`git status --short \
            | awk '{print $1}' \
            | sort | uniq -c \
            | tr '\n' ' ' \
            | sed -E 's/([0-9]+) /\1/g; s/  */ /g; s/ *$//'`

        stash_size=`git stash list | wc -l | sed 's/ //g'`
        stash_icon=" \e[0;92m≡\033[0m"
        printf "[$branch_str]$stat$stash_icon$stash_size"
        return 0
    fi
}

#################################################
## PS1 : date time username@hostname path (newline)
export PS1="\[\033[38;5;63m\]\$(date +%Y-%m-%d) \
\[\033[38;5;11m\]\t \
\[\033[38;5;10m\]\u@\
\[\033[38;5;208m\]\h \
\[\033[38;5;45m\]\w \
\[$(tput sgr0)\]\$(gbr) \
\n\
\[$(tput sgr0)\]> \[$(tput sgr0)\]"


#################################################
## PATH
export PATH=/usr/local/bin:/usr/local/sbin:/Users/raymondk/Library/Python/3.8/bin:/opt/homebrew/bin:$PATH

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

[ -s "/Users/raymondk/.scm_breeze/scm_breeze.sh" ] && source "/Users/raymondk/.scm_breeze/scm_breeze.sh"
